export const titleToHero = {
  "Iron Man": "iron-man",
  "Iron Man 2": "iron-man",
  "Iron Man 3": "iron-man",

  "The Incredible Hulk": "hulk",

  "Captain America: The First Avenger": "captain-america",
  "Captain America: The Winter Soldier": "captain-america",
  "Captain America: Civil War": "captain-america",
  "Captain America: Brave New Order": "falcon",

  "Thor": "thor",
  "Thor: The Dark World": "thor",
  "Thor: Ragnarok": "thor",
  "Thor: Love and Thunder": "thor",

  "Doctor Strange": "doctor-strange",
  "Doctor Strange in the Multiverse of Madness": "doctor-strange",

  "Spider-Man: Homecoming": "spider-man",
  "Spider-Man: Far From Home": "spider-man",
  "Spider-Man: No Way Home": "spider-man",
  "Spider-Man: Brand New Day": "spider-man",

  "Black Panther": "black-panther",
  "Black Panther: Wakanda Forever": "black-panther",

  "Ant-Man": "antman",
  "Ant-Man and The Wasp": "antman",
  "Ant-Man and The Wasp: Quantumania": "antman",

  "Guardians of the Galaxy": "guardians",
  "Guardians of the Galaxy Vol. 2": "guardians",
  "Guardians of the Galaxy Vol. 3": "guardians",

  "Captain Marvel": "captain-marvel",
  "The Marvels": "captain-marvel",

  "Shang-Chi and The Legend of The Ten Rings": "shang-chi",
  "Black Widow": "black-widow",
  "Eternals": "eternals",
  "Deadpool & Wolverine": "deadpool",
  "Thunderbolts*": "thunderbolts",
  "The Fantastic Four: First Steps": "fantastic-four",

  "WandaVision": "scarlet-witch",
  "The Falcon and The Winter Soldier": "falcon",
  "Loki": "loki",
  "What If...?": "watcher",
  "Hawkeye": "hawkeye",
  "Moon Knight": "moon-knight",
  "Ms. Marvel": "ms-marvel",
  "I Am Groot": "groot",
  "She Hulk Attorney at Law": "she-hulk",
  "Werewolf By Night": "werewolf",
  "The Guardians of the Galaxy Holiday Special": "guardians",
  "Secret Invasion": "nick-fury",
  "Echo": "echo",
  "Agatha All Along": "agatha",
  "Daredevil: Born Again": "daredevil",
  "Ironheart": "iron-Heart",

  "X-Men '97": "x-men",
  "Your Friendly Neighborhood Spider-Man": "spider-man",
  "Eyes of Wakanda": "black-panther",
};

export const heroToColor = {
    "iron-man": "ring-amber-400",
    "hulk": "ring-green-700",
    "thor": "ring-red-800",
    "captain-america": "ring-blue-800",
    "black-widow": "ring-stone-700",
    "falcon": "ring-blue-600",
    "guardians": "ring-purple-800",
    "doctor-strange": "ring-cyan-800",
    "spider-man": "ring-red-600",
    "black-panther": "ring-black",
    "antman": "ring-gray-400",
    "captain-marvel": "ring-yellow-300",
    "shang-chi": "ring-red-950",
    "eternals": "ring-orange-200",
    "deadpool": "ring-red-700",
    "thunderbolts": "ring-yellow-700",
    "fantastic-four": "ring-sky-500",
    "scarlet-witch": "ring-red-500",
    "loki": "ring-green-500",
    "watcher": "ring-violet-600",
    "hawkeye": "ring-purple-500",
    "moon-knight": "ring-gray-400",
    "ms-marvel": "ring-pink-600",
    "groot": "ring-lime-800",
    "she-hulk": "ring-green-800",
    "werewolf": "ring-neutral-700",
    "nick-fury": "ring-gray-700",
    "echo": "ring-neutral-300",
    "agatha": "ring-fuchsia-800",
    "daredevil": "ring-red-900",
    "iron-Heart": "ring-rose-800",
    "wolverine": "ring-yellow-500",
    "x-men": "ring-orange-700"
}